stages:
  - stage: CI
    displayName: "Build CI"
    jobs:

      # ----------------- FRONTEND -----------------
      - job: BuildFrontend
        displayName: "Build Frontend"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: "Usar Node.js"
          
          - script: |
              cd tp4/frontend
              npm install
              npm run build
            displayName: "Instalar dependencias y compilar frontend"

          # Publicar el frontend como artefacto

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)/frontend/dist'
              ArtifactName: 'frontend-dist'
            displayName: 'Publicar Artefactos del Frontend'


      # ----------------- ADMIN API -----------------
      - job: BuildAdminApi
        displayName: "Compilar admin-api"
        steps:
          - task: GoTool@0
            inputs:
              version: '1.24.x'
            displayName: "Usar Go"

          - script: |
              cd tp4/backend/admin-api
              go mod tidy
              go build -o dist/bin/admin-api ./...
            displayName: "Compilar admin-api"

          # Publicar binario
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/backend/admin-api/dist/bin'
              artifact: 'admin-api-bin'
            displayName: "Publicar artefacto admin-api"

      # ----------------- SEARCH API -----------------
      - job: BuildSearchApi
        displayName: "Compilar search-api"
        steps:
          - task: GoTool@0
            inputs:
              version: '1.24.x'

          - script: |
              cd tp4/backend/search-api
              go mod tidy
              go build -o dist/bin/search-api ./...
            displayName: "Compilar search-api"

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/backend/search-api/dist/bin'
              artifact: 'search-api-bin'
            displayName: "Publicar artefacto search-api"

      # ----------------- CURSOS API -----------------
      - job: BuildCursosApi
        displayName: "Compilar cursos-api"
        steps:
          - task: GoTool@0
            inputs:
              version: '1.24.x'

          - script: |
              cd tp4/backend/cursos-api
              go mod tidy
              go build -o dist/bin/cursos-api ./...
            displayName: "Compilar cursos-api"

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/backend/cursos-api/dist/bin'
              artifact: 'cursos-api-bin'
            displayName: "Publicar artefacto cursos-api"

      # ----------------- USERS API -----------------
      - job: BuildUsersApi
        displayName: "Compilar users-api"
        steps:
          - task: GoTool@0
            inputs:
              version: '1.24.x'

          - script: |
              cd tp4/backend/users-api
              go mod tidy
              go build -o dist/bin/users-api ./...
            displayName: "Compilar users-api"

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/backend/users-api/dist/bin'
              artifact: 'users-api-bin'
            displayName: "Publicar artefacto users-api"
