trigger:
  branches:
    include:
      - main

stages:
  - stage: CI
    displayName: "Integración Continua"
    jobs:
      - job: Build_Frontend
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "18.x"
            displayName: "Usar Node.js"

          - script: |
              cd frontend
              ls -la
              npm ci
              npm run build
            displayName: "Instalar dependencias y compilar frontend"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "frontend/dist"
              ArtifactName: "frontend"
              publishLocation: "Container"

      - job: Build_Backend
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - script: |
              go version
              cd backend
              go mod tidy
              go build -o bin/app ./...
            displayName: "Compilar backend Go"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "backend/bin"
              ArtifactName: "backend"
              publishLocation: "Container"
