trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: CI
    displayName: "Build CI"
    jobs:

      # ----------------- FRONTEND -----------------
      - job: BuildFrontend
        displayName: "Build Frontend"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: "Usar Node.js"
          
          - script: |
              cd tp4/frontend
              npm install   # si no tenés package-lock.json válido
              npm run build
            displayName: "Instalar dependencias y compilar frontend"

         # Publicar el frontend como artefacto
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: 'tp4/frontend/dist'
              artifact: 'frontend-dist'
            displayName: "Publicar artefacto frontend"

      # ----------------- ADMIN API -----------------
      - job: BuildAdminApi
        displayName: "Compilar admin-api"
        steps:
          - task: GoTool@0
            inputs:
              version: '1.24.x'
            displayName: "Usar Go"

          - script: |
              cd tp4/backend/admin-api
              go mod tidy
              go build ./...
            displayName: "Compilar admin-api"

           # Publicar binario
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: 'tp4/backend/admin-api/dist/bin'
              artifact: 'admin-api-bin'
            displayName: "Publicar artefacto admin-api"

      # ----------------- SEARCH API -----------------
      - job: BuildSearchApi
        displayName: "Compilar search-api"
        steps:
          - task: GoTool@0
            inputs:
              version: '1.24.x'
          - script: |
              cd tp4/backend/search-api
              go mod tidy
              go build ./...
            displayName: "Compilar search-api"

          - task: PublishPipelineArtifact@1
                      inputs:
                        targetPath: 'tp4/backend/search-api/dist/bin'
                        artifact: 'search-api-bin'
                      displayName: "Publicar artefacto search-api"

  

      # ----------------- CURSOS API -----------------
      - job: BuildCursosApi
        displayName: "Compilar cursos-api"
        steps:
          - task: GoTool@0
            inputs:
              version: '1.24.x'
          - script: |
              cd tp4/backend/cursos-api
              go mod tidy
              go build ./...
            displayName: "Compilar cursos-api"

          - task: PublishPipelineArtifact@1
          inputs:
            targetPath: 'tp4/backend/cursos-api/dist/bin'
            artifact: 'cursos-api-bin'
          displayName: "Publicar artefacto cursos-api"

      # ----------------- USERS API -----------------
      - job: BuildUsersApi
        displayName: "Compilar users-api"
        steps:
          - task: GoTool@0
            inputs:
              version: '1.24.x'
          - script: |
              cd tp4/backend/users-api
              go mod tidy
              go build ./...
            displayName: "Compilar users-api"

          - task: PublishPipelineArtifact@1
              inputs:
                targetPath: 'tp4/backend/users-api/dist/bin'
                artifact: 'users-api-bin'
              displayName: "Publicar artefacto users-api"

      